export interface StudyEvidence {
  id: string;
  stat: string;
  title: string;
  finding: string;
  source: string;
  fullCitation: string;
  doiOrUrl?: string;
  howItShapes: string;
  category: "Clinician Time" | "AI Scribing" | "Early Warning" | "Operations" | "National Rail" | "Lab Quality";
}

export const EVIDENCE_STUDIES: StudyEvidence[] = [
  {
    id: "sinsky-2016",
    stat: "~2 hrs",
    title: "Physician Time Allocation in Ambulatory Practice",
    finding: "For every hour doctors spend face to face with patients, nearly two more hours go to EHR and desk work, plus 1-2 hours of clerical work at night.",
    source: "Sinsky et al., Annals of Internal Medicine, 2016",
    fullCitation: "Sinsky C, Colligan L, Li L, et al. Allocation of Physician Time in Ambulatory Practice: A Time and Motion Study in 4 Specialties. Annals of Internal Medicine. 2016;165(11):753-760.",
    doiOrUrl: "https://doi.org/10.7326/M16-0961",
    howItShapes: "HospitalOS prioritizes cutting clerical and data entry friction at the root rather than adding more screens for doctors to manage.",
    category: "Clinician Time",
  },
  {
    id: "lukac-2025",
    stat: "9.5% cut",
    title: "Ambient AI Scribes in Clinical Practice (Randomized Controlled Trial)",
    finding: "In a randomized trial of 238 physicians across 14 specialties (72,000 encounters), ambient AI scribes reduced note time by 9.5% with measurable burnout relief, while requiring doctor review for occasional inaccuracies.",
    source: "Lukac et al., NEJM AI, 2025 (RCT, 238 physicians)",
    fullCitation: "Lukac PJ, et al. Ambient AI Scribes in Clinical Practice: A Randomized Trial. NEJM AI, 2025;2(12). Trial NCT06792890.",
    doiOrUrl: "https://doi.org/10.1056/AIoa2501000",
    howItShapes: "Every note generated by HospitalOS is drafted by AI but strictly reviewed, edited, and signed by the licensed clinician before commit.",
    category: "AI Scribing",
  },
  {
    id: "uw-health-2025",
    stat: "30 min/day",
    title: "Ambient Clinical Documentation Trial",
    finding: "In a clinical trial monitoring documentation load across departments, ambient voice capture saved approximately 30 minutes of documentation per provider per day.",
    source: "UW Health Ambient AI Trial, 2025",
    fullCitation: "University of Wisconsin School of Medicine and Public Health. Ambient AI randomized trial summary, December 2025.",
    doiOrUrl: "https://www.medicine.wisc.edu/news/12162025-department-faculty-lead-new-research-ambient-ai-use-improve-healthcare-practitioner-well-being",
    howItShapes: "Voice-to-notes in Hindi and English is our primary clinical validation module, giving doctors their evenings back.",
    category: "AI Scribing",
  },
  {
    id: "adams-2022",
    stat: "18.7% rel.",
    title: "Prospective Multi-Site Early Warning System Study",
    finding: "Across 5 hospitals and 590,736 monitored patients, patients whose sepsis alert was confirmed by a clinician within 3 hours experienced an 18.7% relative reduction in in-hospital mortality.",
    source: "Adams et al., Nature Medicine, 2022",
    fullCitation: "Adams R, Henry KE, Sridharan A, et al. Prospective, multi-site study of patient outcomes after implementation of the TREWS machine learning-based early warning system for sepsis. Nature Medicine. 2022;28:1455-1460.",
    doiOrUrl: "https://doi.org/10.1036/s41591-022-01894-0",
    howItShapes: "Clinical alerts must be explainable, fast to confirm, and fit seamlessly into doctor workflow rather than triggering alarm fatigue.",
    category: "Early Warning",
  },
  {
    id: "salazar-2022",
    stat: "3 signals",
    title: "Systematic Literature Review of No-Show Predictors",
    finding: "Across 24 machine learning studies, patient age, historical missed appointments, and booking lead time were identified as the strongest predictors of clinic no-shows.",
    source: "Salazar et al., Information, 2022",
    fullCitation: "Salazar LHA, et al. No-Show in Medical Appointments with Machine Learning Techniques: A Systematic Literature Review. Information. 2022;13(11):507.",
    doiOrUrl: "https://doi.org/10.3390/info13110507",
    howItShapes: "HospitalOS uses transparent, lightweight predictive models to trigger automated WhatsApp confirmation reminders and dynamic queue filling.",
    category: "Operations",
  },
  {
    id: "abdm-2026",
    stat: "104 Cr+",
    title: "Ayushman Bharat Digital Mission (ABDM) Scale",
    finding: "Over 104 crore health records are securely linked across 93 crore+ ABHA accounts in India with consent-based architecture at its foundation.",
    source: "Press Information Bureau (PIB), July 2026",
    fullCitation: "Government of India, Press Information Bureau backgrounder on Ayushman Bharat Digital Mission progress and milestones, July 2026.",
    doiOrUrl: "https://static.pib.gov.in/WriteReadData/specificdocs/documents/2026/jul/doc202676912801.pdf",
    howItShapes: "Designed natively for India's digital health stack: instant ABHA QR check-ins, unified health interfaces, and DPDP-compliant consent workflows.",
    category: "National Rail",
  },
];
